Home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home/', views.home,name='home'),
    path('register/', views.register_view, name='register'), 
    path('login/', views.login_view, name='login'), 
    path('logout/', views.logout_view, name='logout'),
]

productManagement/urls.py
#map urls to view fcts
from django.urls import path
from . import views

# urlpatterns=[
#     path('products/', views.index),
    

# ]


urlpatterns = [
    # Add a dynamic URL for the category page
    path('produse/<str:category>/', views.category_products, name='category_products'),
    path('products/', views.index),  # URL pentru coșul de cumpărături,
    path('search/', views.search_feature, name='search_feature'),
    #path('search-suggestions/', views.search_suggestions, name='search_suggestions'),

]

sellWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Radiali/', include('Radiali.urls')),# all the apps which starts with Radiali/ should be handled by the app inside include
    path('productManagement/', include('productManagement.urls')),
    path('Home/', include('Home.urls')),
    path('loginManagement/',include('loginManagement.urls')),
    path('shopping/', include(('shopping.urls', 'shopping'), namespace='shopping')),
    path('', RedirectView.as_view(url='/Home/home', permanent=False), name='index'),
]

shopping/urls.py
# from django.urls import path
# from . import views

# urlpatterns = [
#     path('cart/', views.cart_view, name='cart'),
#     path('sync-cart/', views.sync_cart, name='sync_cart'),
# ]

from django.urls import path
from . import views

app_name = "shopping"

urlpatterns = [
    path("cart/", views.cart_detail, name="cart_detail"),
    path("add/<int:product_id>/", views.add_to_cart, name="add_to_cart"),
    path("remove/<int:cart_item_id>/", views.remove_from_cart, name="remove_from_cart"),
    path("decrease/<int:cart_item_id>/", views.decrease_quantity, name="decrease_quantity"),  
    path("increase/<int:cart_item_id>/", views.increase_quantity, name="increase_quantity"),
    path('process-order/', views.process_order, name='process_order'),  
]

productManagement/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=255)
    price = models.FloatField()
    stock = models.IntegerField()
    image_url = models.URLField(max_length=2083)
    category =models.CharField(max_length=255)
    tehnic_file = models.CharField(max_length=255)
    # category = models.ForeignKey(
    #     Category, related_name="products", on_delete=models.CASCADE
    # )



    def __str__(self):
        return self.name
    
    def get_tehnic_file_path(self):
        return f"/static/search/{self.tehnic_file}"

productManagement/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Product
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse


def index(request):
    products =  Product.objects.all()
    return render(request,'index.html',{'products' : products})


def search_feature(request):
    query = request.GET.get('q', '')
    if query:
        products = Product.objects.filter(
            name__icontains=query
        )
    else:
        products = Product.objects.all()
   
    context = {
        'products': products,
        'search_query': query
    }
    return render(request, 'index.html', context)






def category_products(request, category):
    # Adăugăm debugging pentru a verifica ce primim în URL
    print(f"Categoria primită din URL: {category}")
    
    # Filtrăm produsele după categorie, liniuțele vor rămâne așa cum sunt în baza de date
    products = Product.objects.filter(category__iexact=category.strip())  # Filtrăm după categoria din URL
    
    # Verificăm dacă există produse
    if not products:
        print("Nu sunt produse pentru această categorie.")
    
    # Formatează numele categoriei pentru a-l afișa corect pe pagină:
    # Înlocuim liniuțele cu spațiu și facem prima literă a fiecărui cuvânt mare
    category_name = category.replace('-', ' ').title()  # Înlocuim liniuțele cu spațiu și punem prima literă mare
    
    # Trimitem produsele și categoria la template
    return render(request, 'index.html', {'products': products, 'category': category_name})

productManagement/templates/base.html
<!doctype html>

<link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel="stylesheet">
<link href='https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap' rel="stylesheet">
<link href='https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;600&display=swap' rel="stylesheet">
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
<link href='https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;600&display=swap' rel="stylesheet">


<html lang="en">
  <head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="{% static 'index.js' %}"></script>
    <script src="{% static 'loginBack.js' %}"></script>
    <script src="{% static 'registerBack.js' %}"></script>
    <script src="{% static 'cumparaturi.js' %}"></script>
    <script src="{% static 'search.js' %}"></script>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'popupProduct.js' %}"></script> 
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
  </head>
  <body>
    
   {% block content %}
   {% endblock %}
  </body>
</html>

productManagement/templates/index.html
{% extends 'base.html' %}
<!-- {% include 'loginManagement/templates/login.html' %} -->


{% block content %}
    <!-- <header class="header">
        <div class="header_content">
            <img src="https://seniledecauciuc.ro/assets/images/radiali-logo.png" class="logo">
            <nav class="navbar">
                <a href="/Home/home">Home</a>
                <a href="" id="reg">Inregistreaza-te</a>
                <a href="/loginManagement/login">Intra in cont</a>
                <a href="#despre-noi">Despre</a>
                <a href="/productManagement/products">Produse</a>
                <a href="#">Dealeri</a>
                <a href="#">Contact</a>
            </nav>
        </div>
    </header> -->
    {% include 'navbar.html' %} 
    {% include 'login.html' %}
   

    <br><br>

    <!-- Category Name Header -->
    <h1 class="text-center my-4">Produse </h1>
    <br>
    
    
    <div class="container d-flex justify-content-center">
        <form class="d-flex w-50" method="GET" action="{% url 'search_feature' %}">
            <input
                class="form-control me-2"
                type="search"
                name="q"
                placeholder="Search products..."
                value="{{ search_query|default:'' }}"
                aria-label="Search"
            >
            <button class="btn_whatsapp btn-primary" type="submit">Search</button>
        </form>
    </div>
    
    
    
    

    <br>

    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-4">
            {% if products %}
                {% for product in products %}
                    <div class="col">
                        <div class="card">
                            <img src="{{ product.image_url }}" class="card-img-top" alt="{{ product.name }}">
                            <div class="card-body d-flex flex-column text-center">
                                <h5 class="card-title">{{ product.name }}</h5>
                                <form action="{% url 'shopping:add_to_cart' product.id %}" method="post" class="mt-3">
                                {% csrf_token %}
                                <div class="input-group mb-3">
                                    <input type="number" name="quantity" class="form-control" placeholder="Quantity" min="1" value="1" required>
                                    <button type="submit" class="add-to-cart-btn" >Add to Cart</button>
                                </div>
                            </form>
                                


                            
                            
                                <div class="mt-auto">
                                    <a href="http://Wa.me/+40767594267" class="btn_whatsapp">Prețul</a>
                                    <!-- Butonul pentru vizualizarea imaginii -->
                                    <button class="btn_whatsapp btn-primary" data-bs-toggle="modal" data-bs-target="#imageModal{{ product.id }}">Detalii</button>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Modalul care va afișa imaginea produsului pe tot ecranul -->
                    <div class="modal fade" id="imageModal{{ product.id }}" tabindex="-1" aria-labelledby="imageModalLabel{{ product.id }}" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <!-- Butonul X pentru închidere -->
                                    <button type="button" class="bx bx-x closeBtn" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <img src="{{ product.get_tehnic_file_path }}" class="img-fluid" alt="{{ product.name }}">
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <p class="text-center">Nu sunt produse disponibile.</p>
            {% endif %}
        </div>
    </div>
    


{% include 'footer.html' %}    
{% endblock %}